//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forza_Mods_AIO.Properties;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase 
{
        
    private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
    public static Settings Default => defaultInstance;
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string Up 
    {
        get => ((string)(this["Up"]));
        set => this["Up"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string Down 
    {
        get => ((string)(this["Down"]));
        set => this["Down"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string Left 
    {
        get => ((string)(this["Left"]));
        set => this["Left"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string Right 
    {
        get => ((string)(this["Right"]));
        set => this["Right"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string Confirm 
    {
        get => ((string)(this["Confirm"]));
        set => this["Confirm"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string Leave 
    {
        get => ((string)(this["Leave"]));
        set => this["Leave"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string RapidAdjust 
    {
        get => ((string)(this["RapidAdjust"]));
        set => this["RapidAdjust"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string OverlayVisibility 
    {
        get => ((string)(this["OverlayVisibility"]));
        set => this["OverlayVisibility"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ControllerUp 
    {
        get => ((string)(this["ControllerUp"]));
        set => this["ControllerUp"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ControllerDown 
    {
        get => ((string)(this["ControllerDown"]));
        set => this["ControllerDown"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ControllerLeft 
    {
        get => ((string)(this["ControllerLeft"]));
        set => this["ControllerLeft"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ControllerRight 
    {
        get => ((string)(this["ControllerRight"]));
        set => this["ControllerRight"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ControllerConfirm 
    {
        get => ((string)(this["ControllerConfirm"]));
        set => this["ControllerConfirm"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ControllerLeave 
    {
        get => ((string)(this["ControllerLeave"]));
        set => this["ControllerLeave"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ControllerRapidAdjust 
    {
        get => ((string)(this["ControllerRapidAdjust"]));
        set => this["ControllerRapidAdjust"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ControllerOverlayVisibility 
    {
        get => ((string)(this["ControllerOverlayVisibility"]));
        set => this["ControllerOverlayVisibility"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string JumpHack 
    {
        get => ((string)(this["JumpHack"]));
        set => this["JumpHack"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string BrakeHack 
    {
        get => ((string)(this["BrakeHack"]));
        set => this["BrakeHack"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string Velocity 
    {
        get => ((string)(this["Velocity"]));
        set => this["Velocity"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string WheelSpeed 
    {
        get => ((string)(this["WheelSpeed"]));
        set => this["WheelSpeed"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string JumpHackController 
    {
        get => ((string)(this["JumpHackController"]));
        set => this["JumpHackController"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string BrakeHackController 
    {
        get => ((string)(this["BrakeHackController"]));
        set => this["BrakeHackController"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string VelocityController 
    {
        get => ((string)(this["VelocityController"]));
        set => this["VelocityController"] = value;
    }
        
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string WheelSpeedHackController 
    {
        get => ((string)(this["WheelSpeedHackController"]));
        set => this["WheelSpeedHackController"] = value;
    }
}